export interface PricingPackage {
  name: string;
  price: string | null;
  isCustom: boolean;
  features: string[];
  note?: string;
  highlighted?: boolean;
}

export interface PricingService {
  slug: string;
  title: string;
  category: string;
  description: string;
  color: string;
  icon: string;
  startingFrom: string;
  packages: PricingPackage[];
}

export const pricingServices: PricingService[] = [
  {
    slug: 'graphic-design',
    title: 'Graphic Design',
    category: 'Creative',
    description: 'Professional visual design for brands, social media, and e-commerce — crafted to capture attention and drive engagement.',
    color: '#EC4899',
    icon: 'Palette',
    startingFrom: 'Rs. 1,000',
    packages: [
      {
        name: 'Logo Design',
        price: 'Rs. 4,999',
        isCustom: false,
        features: [
          'Custom logo concepts (3 variations)',
          'Vector file delivery (AI, SVG, PNG)',
          'Color palette included',
          'Revision rounds: 2',
          '48-hr turnaround',
        ],
      },
      {
        name: 'Brand Style Guide',
        price: 'Rs. 9,999',
        isCustom: false,
        features: [
          'Logo usage rules',
          'Typography system',
          'Color palette & codes',
          'Iconography & imagery guidelines',
          'PDF delivery',
        ],
      },
      {
        name: 'Business Cards & Stationery',
        price: 'Rs. 1,999',
        isCustom: false,
        features: [
          'Front & back business card design',
          'Letterhead design',
          'Envelope design',
          'Print-ready files',
        ],
      },
      {
        name: 'Social Media Post Design',
        price: 'Rs. 1,000',
        isCustom: false,
        features: [
          'Per post pricing',
          'Platform-optimized dimensions',
          'On-brand design',
          'Source file included',
        ],
        note: 'Per post',
      },
      {
        name: 'Ecommerce Store Banner',
        price: 'Rs. 1,999',
        isCustom: false,
        features: [
          'Per banner pricing',
          'Desktop & mobile versions',
          'Conversion-focused layout',
          'Source file included',
        ],
        note: 'Per banner',
      },
      {
        name: 'Monthly Design Package',
        price: null,
        isCustom: true,
        features: [
          'Unlimited design requests',
          'Dedicated designer',
          'Social posts, banners & ads',
          'Priority turnaround',
          'Customizable per brand requirements',
        ],
        highlighted: true,
      },
    ],
  },
  {
    slug: 'video-editing',
    title: 'Video Editing & Post-Production',
    category: 'Creative',
    description: 'From quick social cuts to full corporate productions — premium video editing, motion graphics, and AI-powered content creation.',
    color: '#F87171',
    icon: 'Video',
    startingFrom: 'Rs. 2,999',
    packages: [
      {
        name: 'Video Editing & Post-Production',
        price: 'Rs. 2,999',
        isCustom: false,
        features: [
          'Color grading & correction',
          'Audio syncing & cleanup',
          'Subtitle & caption overlay',
          'Social-media-ready export',
        ],
      },
      {
        name: 'Video Repurposing',
        price: 'Rs. 2,999',
        isCustom: false,
        features: [
          'Long-form to short-form clips',
          'Aspect ratio conversion',
          'Hook & CTA editing',
          'Multi-platform delivery',
        ],
      },
      {
        name: 'Intro & Outro Videos',
        price: 'Rs. 4,999',
        isCustom: false,
        features: [
          'Branded animated intro',
          'Animated outro with CTA',
          'Logo reveal included',
          'HD delivery',
        ],
      },
      {
        name: 'Video Templates Editing',
        price: 'Rs. 7,000',
        isCustom: false,
        features: [
          'Social & marketing videos',
          'E-commerce product videos',
          'Template customization',
          'Batch delivery',
        ],
      },
      {
        name: 'Video Ads & Commercials',
        price: 'Rs. 4,999',
        isCustom: false,
        features: [
          'Ad-ready format',
          'Multiple aspect ratios',
          'Hook-optimized editing',
          'Motion graphics overlay',
        ],
      },
      {
        name: 'UGC Videos',
        price: 'Rs. 16,000',
        isCustom: false,
        features: [
          '3 ad variations included',
          '1 model face + 1 product',
          'Different hooks & scripts',
          'Script writing included',
          'Package customizable per model',
        ],
        note: '3 Ads + Model + Script',
      },
      {
        name: 'Logo Animation',
        price: 'Rs. 5,999',
        isCustom: false,
        features: [
          'Animated logo reveal',
          'Loop & single-play versions',
          'Transparent background export',
          'MP4 & GIF delivery',
        ],
      },
      {
        name: 'Lottie & Web Animation',
        price: 'Rs. 15,000',
        isCustom: false,
        features: [
          'Lottie JSON export',
          'Lightweight web animations',
          'Interactive state support',
          'React & HTML compatible',
        ],
      },
      {
        name: 'Video Art Creation (AI)',
        price: 'Rs. 9,999',
        isCustom: false,
        features: [
          'AI-generated video content',
          'Brand-style-consistent visuals',
          'HD output',
          'Multiple scene variations',
        ],
      },
      {
        name: '3D Product Animation',
        price: 'Rs. 35,000',
        isCustom: false,
        features: [
          'Full 3D product model',
          '360° rotation animation',
          'Studio-quality lighting',
          '4K export',
        ],
      },
      {
        name: 'Corporate Videos',
        price: 'Rs. 60,000',
        isCustom: false,
        features: [
          'Script & storyboard included',
          'Professional editing',
          'Motion graphics integration',
          'Voiceover (male/female)',
          'Full post-production',
        ],
      },
      {
        name: 'AI UGC',
        price: 'Rs. 3,999',
        isCustom: false,
        features: [
          'AI-generated presenter',
          'Script writing included',
          'Ad-ready format',
          'Multiple hooks',
        ],
      },
      {
        name: 'Real Estate Promos',
        price: 'Rs. 9,999',
        isCustom: false,
        features: [
          'Cinematic property walkthrough',
          'Drone footage editing',
          'Text overlays & branding',
          'Social & listing formats',
        ],
      },
      {
        name: 'Custom Video Package',
        price: null,
        isCustom: true,
        features: [
          'Tailored to your content goals',
          'Volume pricing available',
          'Dedicated editor assigned',
          'Priority delivery',
          'Unlimited revision rounds',
        ],
        highlighted: true,
      },
    ],
  },
  {
    slug: 'seo-packages',
    title: 'SEO Services',
    category: 'Search',
    description: 'Data-driven SEO strategies that move the needle — from technical audits to full content and backlink campaigns.',
    color: '#F59E0B',
    icon: 'Search',
    startingFrom: 'Rs. 1,000',
    packages: [
      {
        name: 'On-Page + Off-Page SEO',
        price: 'Rs. 50,000',
        isCustom: false,
        features: [
          'Full on-page optimization',
          'Off-page authority building',
          'Keyword mapping',
          'Content recommendations',
          'Monthly reporting',
        ],
      },
      {
        name: 'E-Commerce Product SEO',
        price: 'Rs. 1,000',
        isCustom: false,
        features: [
          'Per product optimization',
          'Title & description SEO',
          'Schema markup',
          'Image alt optimization',
        ],
        note: 'Per product',
      },
      {
        name: 'Google Map SEO',
        price: 'Rs. 7,000',
        isCustom: false,
        features: [
          'Google Business Profile optimization',
          'Local citation building',
          'Review strategy',
          'Map pack ranking focus',
        ],
      },
      {
        name: 'Blog SEO Script',
        price: 'Rs. 6,000',
        isCustom: false,
        features: [
          'Per blog SEO scripting',
          'Keyword-optimized structure',
          'Internal linking map',
          'Meta title & description',
        ],
        note: 'Per blog',
      },
      {
        name: 'Local SEO Package',
        price: 'Rs. 25,000',
        isCustom: false,
        features: [
          'Local keyword research',
          'NAP consistency audit',
          'Local citation building',
          'Google Maps optimization',
          'Monthly local reporting',
        ],
      },
      {
        name: 'Technical SEO Package',
        price: 'Rs. 30,000',
        isCustom: false,
        features: [
          'Core Web Vitals optimization',
          'Site speed improvements',
          'Schema markup implementation',
          'Crawl error resolution',
          'XML sitemap & robots.txt',
        ],
      },
      {
        name: 'Keyword Research Package',
        price: 'Rs. 15,000',
        isCustom: false,
        features: [
          'Comprehensive keyword universe',
          'Competitor gap analysis',
          'Intent mapping',
          'Priority keyword roadmap',
        ],
      },
      {
        name: 'Website Audit Package',
        price: 'Rs. 12,000',
        isCustom: false,
        features: [
          'Full technical SEO audit',
          'On-page issues report',
          'Speed & UX review',
          'Competitor benchmark',
          'Action plan included',
        ],
      },
      {
        name: 'Backlink Building Package',
        price: 'Rs. 20,000',
        isCustom: false,
        features: [
          'High-DA link acquisition',
          'Guest posting outreach',
          'Broken link building',
          'Monthly link report',
        ],
      },
      {
        name: 'Content SEO Strategy',
        price: 'Rs. 18,000',
        isCustom: false,
        features: [
          'Content calendar creation',
          'Pillar & cluster architecture',
          'Topic authority mapping',
          'Internal link strategy',
        ],
      },
      {
        name: 'Custom SEO Package',
        price: null,
        isCustom: true,
        features: [
          'Fully bespoke SEO strategy',
          'Multi-location or multi-site support',
          'Dedicated SEO specialist',
          'Weekly reporting',
          'Scale with your business',
        ],
        highlighted: true,
      },
    ],
  },
  {
    slug: 'courier-management',
    title: 'Courier & Order Management',
    category: 'Operations',
    description: 'End-to-end courier setup, order tracking, return management, and data reporting — so you can focus on selling.',
    color: '#34D399',
    icon: 'Package',
    startingFrom: 'Rs. 7,999',
    packages: [
      {
        name: 'Courier Setup & Guiding',
        price: 'Rs. 7,999',
        isCustom: false,
        features: [
          'Courier account setup',
          'Integration with your store',
          'Shipping rules configuration',
          'Team training & handoff',
          'Excel sheet data management included',
        ],
      },
      {
        name: 'Order Packing & Return Management',
        price: null,
        isCustom: true,
        features: [
          'Packing station setup guidance',
          'Return label generation',
          'Return policy structuring',
          'Monthly performance report included',
        ],
      },
      {
        name: 'Return Orders Checking & Sorting',
        price: null,
        isCustom: true,
        features: [
          'Returned item categorization',
          'Condition grading',
          'Restock vs. write-off decisions',
          'Reporting dashboard',
        ],
      },
      {
        name: 'Product Testing & Market Purchase',
        price: null,
        isCustom: true,
        features: [
          'Market sourcing & purchase',
          'Product quality testing',
          'Competitor benchmarking',
          'Winning product report',
        ],
      },
      {
        name: 'Full Operations Package',
        price: null,
        isCustom: true,
        features: [
          'All services bundled',
          'Excel sheet data management',
          'Monthly performance report',
          'Dedicated operations manager',
          'Fully customizable per requirements',
        ],
        highlighted: true,
      },
    ],
  },
  {
    slug: 'performance-ads',
    title: 'Performance Marketing',
    category: 'Ads',
    description: 'Results-obsessed paid advertising across Meta, Google, Snapchat, YouTube, and LinkedIn — built to scale revenue.',
    color: '#8B5CF6',
    icon: 'TrendingUp',
    startingFrom: 'Rs. 30,000',
    packages: [
      {
        name: 'Performance Marketing — Project',
        price: 'Rs. 30,000',
        isCustom: false,
        features: [
          'Meta Ads (Facebook & Instagram)',
          'Google Ads (Search, Display & Shopping)',
          'Snapchat Ads',
          'YouTube Ads',
          'LinkedIn Ads',
          'Campaign setup, management & optimization',
          'Weekly performance reporting',
        ],
        note: 'Ad budget is separate',
      },
      {
        name: 'Commission Model',
        price: '10% of Gross Sales',
        isCustom: false,
        features: [
          '1M Sales Target basis',
          'No fixed monthly fee',
          'All ad platforms included',
          'Full campaign management',
          'Scale with your revenue',
        ],
        note: 'Performance-based pricing',
      },
      {
        name: 'Custom Ads Package',
        price: null,
        isCustom: true,
        features: [
          'Tailored to your business goals',
          'Custom platform mix',
          'Funnel strategy included',
          'Landing page creation',
          'A/B testing & scaling plan',
        ],
        highlighted: true,
      },
    ],
  },
  {
    slug: 'digital-marketing',
    title: 'Digital Marketing',
    category: 'Marketing',
    description: 'Full-spectrum digital marketing — social media, content, brand awareness, and lead generation under one unified strategy.',
    color: '#06B6D4',
    icon: 'Globe',
    startingFrom: 'Rs. 50,000',
    packages: [
      {
        name: 'Digital Marketing — Project',
        price: 'Rs. 50,000',
        isCustom: false,
        features: [
          'Social Media Marketing (Facebook, Instagram, TikTok)',
          'Content Planning & Strategy',
          'Post Design & Scheduling',
          'Brand Awareness Campaigns',
          'Lead Generation Campaigns',
          'Basic Community Management',
          'Analytics & Performance Reporting',
        ],
      },
      {
        name: 'Custom Digital Marketing Package',
        price: null,
        isCustom: true,
        features: [
          'Multi-channel strategy',
          'Influencer integration',
          'Paid + organic combined',
          'Dedicated account manager',
          'Scale-up roadmap included',
        ],
        highlighted: true,
      },
    ],
  },
  {
    slug: 'social-media-marketing',
    title: 'Social Media Marketing',
    category: 'Social',
    description: 'Strategic social media management across Facebook, Instagram, and TikTok — growing your audience and driving real engagement.',
    color: '#EC4899',
    icon: 'Share2',
    startingFrom: 'Rs. 20,000',
    packages: [
      {
        name: 'Social Media Marketing — Project',
        price: 'Rs. 20,000',
        isCustom: false,
        features: [
          'Facebook & Instagram Page Management',
          'Content Strategy & Monthly Plan',
          'Post Design & Publishing',
          'Caption Writing & Hashtag Research',
          'Audience Engagement (Comments & DMs)',
          'Basic Brand Growth Strategy',
          'Monthly Performance Report',
          'Platforms: Facebook, Instagram, TikTok (Basic)',
        ],
      },
      {
        name: 'Custom Social Package',
        price: null,
        isCustom: true,
        features: [
          'Add TikTok, YouTube, LinkedIn',
          'Influencer collaboration',
          'Paid social campaigns',
          'Advanced analytics dashboard',
          'Community growth campaigns',
        ],
        highlighted: true,
      },
    ],
  },
  {
    slug: 'video-production',
    title: 'Video Production',
    category: 'Creative',
    description: 'On-location and studio video production — B-roll, A-roll, and packaged content that converts across every platform.',
    color: '#F97316',
    icon: 'Film',
    startingFrom: 'Rs. 4,000',
    packages: [
      {
        name: 'B-Roll Video',
        price: 'Rs. 4,000',
        isCustom: false,
        features: [
          'Hand shots & product visuals',
          'Professional voiceover (M/F)',
          'Color graded & edited',
          'Ad-ready social format',
        ],
        note: 'Per video',
      },
      {
        name: 'A-Roll Video',
        price: 'Rs. 15,000',
        isCustom: false,
        features: [
          'On-camera model face video',
          'Script + 3 different hooks',
          '3 script variations',
          'Professional editing',
          'Ad-ready format',
        ],
        note: 'Per video',
      },
      {
        name: '3 Videos Package',
        price: 'Rs. 15,000',
        isCustom: false,
        features: [
          '1 product covered',
          'Script writing (hooks + storylines)',
          'Model/Actor selection (M/F)',
          'Basic editing & color correction',
          'Voiceover (M/F as needed)',
          'Ad-ready format for social media',
        ],
        note: 'Normal Package',
      },
      {
        name: 'Custom Video Production',
        price: null,
        isCustom: true,
        features: [
          'Multi-product coverage',
          'Full production crew',
          'Advanced post-production',
          'Bulk video discounts',
          'Tailored for your brand',
        ],
        highlighted: true,
      },
    ],
  },
  {
    slug: 'influencer-content',
    title: 'Influencer Video Content',
    category: 'Creative',
    description: 'Authentic influencer-style content — B-roll to full A-roll packages, priced by influencer tier, content type, and volume.',
    color: '#A78BFA',
    icon: 'Star',
    startingFrom: 'Custom Pricing',
    packages: [
      {
        name: 'B-Roll (Influencer Style)',
        price: null,
        isCustom: true,
        features: [
          'Hand shots + product visuals',
          'Voiceover (M/F per brand)',
          'Influencer-style editing',
          'Platform-optimized format',
        ],
      },
      {
        name: 'A-Roll (Influencer Face)',
        price: null,
        isCustom: true,
        features: [
          'Model face video',
          'Script + 3 different hooks',
          'Multiple ad variations',
          'Hook-optimized for conversion',
        ],
      },
      {
        name: 'Complete Influencer Package',
        price: null,
        isCustom: true,
        features: [
          'B-Roll + A-Roll + Editing + Script',
          'Micro / Mid / High-tier influencer',
          'Number of videos negotiable',
          'Script complexity & hooks',
          'Product category-specific',
        ],
        note: 'Price based on influencer level & content type',
      },
      {
        name: 'Full Custom Campaign',
        price: null,
        isCustom: true,
        features: [
          'Influencer selection & vetting',
          'Campaign strategy & briefs',
          'Multi-video package',
          'Distribution guidance',
          'ROI tracking setup',
        ],
        highlighted: true,
      },
    ],
  },
  {
    slug: 'web-dev',
    title: 'Website & Development',
    category: 'Development',
    description: 'High-converting websites, e-commerce stores, landing pages, and custom web apps — built for performance and results.',
    color: '#F43F5E',
    icon: 'Code',
    startingFrom: 'Custom Pricing',
    packages: [
      {
        name: 'E-Commerce Website',
        price: null,
        isCustom: true,
        features: [
          'Shopify or WordPress setup',
          'Product catalog import',
          'Payment gateway integration',
          'Mobile-responsive design',
          'Speed optimization',
        ],
        note: 'Shopify / WordPress',
      },
      {
        name: 'Landing Page',
        price: null,
        isCustom: true,
        features: [
          'High-conversion sales page',
          'A/B test-ready structure',
          'Lead capture forms',
          'Pixel & analytics setup',
          'Fast delivery',
        ],
        note: 'High Conversion',
      },
      {
        name: 'Multi-Vendor Marketplace',
        price: null,
        isCustom: true,
        features: [
          'Custom vendor onboarding',
          'Commission & payout logic',
          'Admin dashboard',
          'Real-time order tracking',
          'Scalable architecture',
        ],
      },
      {
        name: 'Website Maintenance',
        price: null,
        isCustom: true,
        features: [
          'Speed & Core Web Vitals optimization',
          'Security updates',
          'Plugin/dependency updates',
          'Uptime monitoring',
          'Monthly health report',
        ],
      },
      {
        name: 'UI/UX Design',
        price: null,
        isCustom: true,
        features: [
          'User research & wireframes',
          'High-fidelity Figma design',
          'Mobile & desktop responsive',
          'Design system delivery',
          'Developer handoff',
        ],
      },
      {
        name: 'Fully Custom Build',
        price: null,
        isCustom: true,
        features: [
          'Bespoke scope & architecture',
          'Full-stack development',
          'Dedicated engineering team',
          'Post-launch support',
          'Scalable for growth',
        ],
        highlighted: true,
      },
    ],
  },
  {
    slug: 'brand-identity',
    title: 'Branding Services',
    category: 'Creative',
    description: 'Complete brand identities that tell your story — from naming and strategy to packaging and visual guidelines.',
    color: '#FF6B35',
    icon: 'Award',
    startingFrom: 'Custom Pricing',
    packages: [
      {
        name: 'Complete Brand Identity',
        price: null,
        isCustom: true,
        features: [
          'Logo suite design',
          'Color palette & typography',
          'Brand guidelines document',
          'Brand voice & messaging',
          'Social media branding kit',
        ],
      },
      {
        name: 'Brand Naming & Tagline',
        price: null,
        isCustom: true,
        features: [
          'Brand name ideation',
          'Domain availability check',
          'Tagline creation',
          'Trademark search guidance',
        ],
      },
      {
        name: 'Packaging Design',
        price: null,
        isCustom: true,
        features: [
          'Product box design',
          'Label design',
          'Print-ready files',
          'Mockup presentation',
        ],
        note: 'Product Boxes, Labels',
      },
      {
        name: 'Brand Strategy & Positioning',
        price: null,
        isCustom: true,
        features: [
          'Competitor analysis',
          'Target audience profiling',
          'Brand positioning statement',
          'Growth strategy roadmap',
        ],
      },
      {
        name: 'Full Branding Package',
        price: null,
        isCustom: true,
        features: [
          'All branding services bundled',
          'Strategy + identity + packaging',
          'Dedicated brand strategist',
          'Ongoing brand consulting',
          'Fully customizable scope',
        ],
        highlighted: true,
      },
    ],
  },
  {
    slug: 'content-creation',
    title: 'Content Creation',
    category: 'Creative',
    description: 'Viral reels, UGC ads, product photography, and AI visuals — content that stops the scroll and drives action.',
    color: '#10B981',
    icon: 'Camera',
    startingFrom: 'Custom Pricing',
    packages: [
      {
        name: 'Reels & TikTok Viral Content',
        price: null,
        isCustom: true,
        features: [
          'Hook-first editing style',
          'Trending audio integration',
          'Caption & hashtag strategy',
          'Platform-native formats',
        ],
      },
      {
        name: 'UGC Content for Ads',
        price: null,
        isCustom: true,
        features: [
          'User-generated style videos',
          'Script + shooting + editing',
          'Ad-ready deliverables',
          'Multiple hooks per video',
        ],
      },
      {
        name: 'Product Photography (Studio)',
        price: null,
        isCustom: true,
        features: [
          'White & lifestyle backgrounds',
          'Multiple angles per product',
          'Color correction & retouching',
          'E-commerce ready exports',
        ],
      },
      {
        name: 'Lifestyle Photography',
        price: null,
        isCustom: true,
        features: [
          'On-location shoots',
          'Model selection available',
          'Brand-consistent styling',
          'High-res & social exports',
        ],
      },
      {
        name: 'AI Product Mockups & Visuals',
        price: null,
        isCustom: true,
        features: [
          'AI-generated product scenes',
          'Multiple backgrounds & styles',
          'Fast 24-hr turnaround',
          'Commercial usage rights',
        ],
      },
      {
        name: 'Full Content Package',
        price: null,
        isCustom: true,
        features: [
          'Photography + video + AI visuals',
          'Monthly retainer available',
          'Dedicated content team',
          'Priority turnaround',
          'Fully customizable scope',
        ],
        highlighted: true,
      },
    ],
  },
  {
    slug: 'marketing-advanced',
    title: 'Advanced Marketing Services',
    category: 'Marketing',
    description: 'Funnels, email automation, WhatsApp CRM, affiliate programs, and influencer campaigns — the full growth stack.',
    color: '#FBBF24',
    icon: 'Layers',
    startingFrom: 'Custom Pricing',
    packages: [
      {
        name: 'Funnel Building',
        price: null,
        isCustom: true,
        features: [
          'Sales funnel architecture',
          'Landing page creation',
          'Upsell & downsell flows',
          'Pixel & tracking setup',
          'A/B testing framework',
        ],
        note: 'Sales Funnel Setup',
      },
      {
        name: 'Email Marketing Automation',
        price: null,
        isCustom: true,
        features: [
          'Email sequence design',
          'Welcome, nurture & cart flows',
          'Platform setup (Klaviyo / MailChimp)',
          'A/B subject line testing',
          'Monthly analytics report',
        ],
      },
      {
        name: 'WhatsApp CRM Marketing',
        price: null,
        isCustom: true,
        features: [
          'WhatsApp Business API setup',
          'Broadcast campaign creation',
          'Automated reply flows',
          'Lead nurture sequences',
          'CRM integration',
        ],
      },
      {
        name: 'Influencer Outreach & Campaigns',
        price: null,
        isCustom: true,
        features: [
          'Influencer identification & vetting',
          'Campaign brief creation',
          'Contract & negotiation support',
          'Content approval workflow',
          'ROI tracking & reporting',
        ],
      },
      {
        name: 'Affiliate Marketing Setup',
        price: null,
        isCustom: true,
        features: [
          'Affiliate program structure',
          'Platform setup',
          'Affiliate recruitment',
          'Commission tracking',
          'Monthly payout management',
        ],
      },
      {
        name: 'Full Growth Stack',
        price: null,
        isCustom: true,
        features: [
          'All advanced services bundled',
          'Unified strategy across channels',
          'Dedicated growth manager',
          'Weekly reporting',
          'Scalable per business goals',
        ],
        highlighted: true,
      },
    ],
  },
  {
    slug: 'ecommerce-support',
    title: 'E-Commerce Support Services',
    category: 'Commerce',
    description: 'Product research, supplier sourcing, fulfillment setup, returns handling, and store optimization — your e-commerce back-office, handled.',
    color: '#38BDF8',
    icon: 'ShoppingBag',
    startingFrom: 'Custom Pricing',
    packages: [
      {
        name: 'Product Hunting',
        price: null,
        isCustom: true,
        features: [
          'Winning product research',
          'Demand & competition analysis',
          'Supplier identification',
          'Profit margin calculation',
          'Detailed product report',
        ],
        note: 'Winning Products Research',
      },
      {
        name: 'Supplier Sourcing',
        price: null,
        isCustom: true,
        features: [
          'Lahore market sourcing',
          'Karachi market sourcing',
          'Sample procurement',
          'Supplier vetting & negotiation',
        ],
        note: 'Local Market Sourcing',
      },
      {
        name: 'Order Fulfillment Setup',
        price: null,
        isCustom: true,
        features: [
          'Fulfillment workflow design',
          'Courier integration',
          'Tracking & notification setup',
          'SLA management',
        ],
      },
      {
        name: 'Return & Customer Support',
        price: null,
        isCustom: true,
        features: [
          'Return policy setup',
          'Customer support scripts',
          'Inbox & WhatsApp management',
          'Escalation workflow',
        ],
      },
      {
        name: 'Store Optimization',
        price: null,
        isCustom: true,
        features: [
          'Conversion rate audit',
          'Product page optimization',
          'Checkout flow improvements',
          'Trust badge & review integration',
          'A/B testing recommendations',
        ],
        note: 'Conversion Increase',
      },
      {
        name: 'Full E-Commerce Operations',
        price: null,
        isCustom: true,
        features: [
          'All support services bundled',
          'Dedicated operations team',
          'Weekly progress reports',
          'KPI dashboard',
          'Fully customizable scope',
        ],
        highlighted: true,
      },
    ],
  },
  {
    slug: 'ai-integrations',
    title: 'AI Integrations',
    category: 'Artificial Intelligence',
    description: 'Embed intelligent AI capabilities into your existing products — chatbots, automation, custom models, and enterprise AI platforms built to scale.',
    color: '#7C3AED',
    icon: 'Brain',
    startingFrom: 'Rs. 35,000',
    packages: [
      {
        name: 'AI Chatbot Integration',
        price: 'Rs. 35,000',
        isCustom: false,
        features: [
          'GPT-4 / Claude API integration',
          'Custom knowledge base setup',
          'Website chat widget',
          'Up to 1,000 queries/day',
          '2-week delivery',
        ],
      },
      {
        name: 'AI Workflow Automation',
        price: 'Rs. 75,000',
        isCustom: false,
        features: [
          '3 AI-powered business workflows',
          'API integrations (OpenAI, Claude, Gemini)',
          'Custom prompt engineering',
          'Analytics dashboard',
          '30-day post-launch support',
        ],
      },
      {
        name: 'AI-Powered Business Suite',
        price: 'Rs. 150,000',
        isCustom: false,
        features: [
          'Custom AI model fine-tuning',
          '5+ workflow automations',
          'CRM & ERP integrations',
          'Real-time data pipelines',
          'Dedicated AI engineer',
          '60-day support',
        ],
        highlighted: false,
      },
      {
        name: 'Enterprise AI Platform',
        price: 'Rs. 250,000',
        isCustom: false,
        features: [
          'Full custom AI platform build',
          'Multi-model orchestration',
          'Private data fine-tuning',
          'API + dashboard + mobile app',
          'SLA & uptime guarantee',
          'Ongoing maintenance included',
        ],
        highlighted: true,
        note: 'Full Enterprise Build',
      },
    ],
  },
  {
    slug: 'business-automations',
    title: 'Business Automations',
    category: 'Automation',
    description: 'End-to-end business process automation — from sales and marketing flows to full operational systems that run without human intervention.',
    color: '#10B981',
    icon: 'Zap',
    startingFrom: 'Rs. 100,000',
    packages: [
      {
        name: 'Starter Automation',
        price: 'Rs. 100,000',
        isCustom: false,
        features: [
          '3 core business workflows automated',
          'CRM automation (HubSpot / Zoho)',
          'Email & notification pipelines',
          'Zapier / Make.com integration',
          '30-day support',
        ],
      },
      {
        name: 'Growth Automation Suite',
        price: 'Rs. 200,000',
        isCustom: false,
        features: [
          '8 automated workflows',
          'Sales + marketing automation',
          'ERP & CRM deep integration',
          'Custom reporting dashboard',
          'Unlimited API connections',
          '60-day support',
        ],
        highlighted: false,
      },
      {
        name: 'Full Business OS',
        price: 'Rs. 350,000',
        isCustom: false,
        features: [
          'Complete business automation (15+ flows)',
          'AI-enhanced decision automation',
          'Custom admin dashboard',
          'Unlimited 3rd-party integrations',
          'Dedicated automation engineer',
          '90-day support + team training',
        ],
        highlighted: true,
        note: 'Complete Automation Stack',
      },
    ],
  },
  {
    slug: 'infrastructure',
    title: 'Infrastructure & DevOps',
    category: 'Engineering',
    description: 'Enterprise-grade cloud infrastructure design, deployment, and managed operations — built for scale, security, and zero downtime.',
    color: '#64748B',
    icon: 'Server',
    startingFrom: 'Rs. 250,000',
    packages: [
      {
        name: 'Infrastructure Setup',
        price: 'Rs. 250,000',
        isCustom: false,
        features: [
          'Cloud infrastructure architecture',
          'AWS / GCP / Azure setup',
          'CI/CD pipeline configuration',
          'Security hardening & IAM',
          'Monitoring & alerting (Grafana)',
          '30-day handoff support',
        ],
      },
      {
        name: 'Enterprise Infrastructure',
        price: 'Rs. 350,000',
        isCustom: false,
        features: [
          'Multi-region deployment',
          'Load balancing & auto-scaling',
          'Kubernetes (EKS/GKE) orchestration',
          'Database clustering & replication',
          'Disaster recovery setup',
          '90-day managed support',
        ],
      },
      {
        name: 'Full Infrastructure Suite',
        price: 'Rs. 450,000',
        isCustom: false,
        features: [
          'Complete enterprise architecture',
          'Microservices infrastructure',
          'Zero-downtime blue/green deployments',
          'Security & compliance audit (SOC2)',
          '24/7 monitoring & incident response',
          'Dedicated DevOps engineer',
          '6-month SLA support',
        ],
        highlighted: true,
        note: 'Enterprise Scale',
      },
    ],
  },
  {
    slug: 'cloud-design',
    title: 'Cloud Architecture & Design',
    category: 'Cloud',
    description: 'Optimised cloud architecture, cost engineering, and migration planning across AWS, GCP, and Azure — designed for performance and savings.',
    color: '#38BDF8',
    icon: 'Cloud',
    startingFrom: 'Rs. 25,000',
    packages: [
      {
        name: 'Cloud Architecture Audit',
        price: 'Rs. 25,000',
        isCustom: false,
        features: [
          'Current infrastructure review',
          'Cost optimisation report',
          'Security gap analysis',
          'Migration readiness score',
          'Action plan & roadmap',
        ],
      },
      {
        name: 'Cloud Migration',
        price: 'Rs. 55,000',
        isCustom: false,
        features: [
          'Full cloud migration planning',
          'AWS / GCP / Azure provisioning',
          'Data migration & validation',
          'Performance & load testing',
          '30-day post-migration support',
        ],
      },
      {
        name: 'Cloud Design & Optimisation',
        price: 'Rs. 85,000',
        isCustom: false,
        features: [
          'Custom cloud architecture blueprint',
          'Multi-cloud strategy design',
          'FinOps cost engineering',
          'Auto-scaling & load balancing',
          'Security compliance (ISO/SOC)',
          '60-day support',
        ],
        highlighted: true,
        note: 'Full Architecture Package',
      },
    ],
  },
  {
    slug: 'blockchain-dev',
    title: 'Blockchain Development',
    category: 'Blockchain',
    description: 'Smart contracts, decentralised applications, and private blockchain networks — engineered for security, transparency, and enterprise adoption.',
    color: '#F59E0B',
    icon: 'Network',
    startingFrom: 'Rs. 80,000',
    packages: [
      {
        name: 'Smart Contract Development',
        price: 'Rs. 80,000',
        isCustom: false,
        features: [
          'Solidity / Rust smart contracts',
          'Unit testing & security audit',
          'Testnet & mainnet deployment',
          'ABI documentation',
          'Post-deployment support',
        ],
      },
      {
        name: 'DApp Development',
        price: 'Rs. 180,000',
        isCustom: false,
        features: [
          'Full-stack decentralised application',
          'Smart contract backend',
          'Web3 React frontend',
          'MetaMask & WalletConnect integration',
          'IPFS / Filecoin storage',
          '60-day support',
        ],
      },
      {
        name: 'Enterprise Blockchain Solution',
        price: null,
        isCustom: true,
        features: [
          'Private / consortium blockchain',
          'Custom consensus mechanism',
          'Enterprise API & admin layer',
          'Identity & access management',
          'Full security audit & compliance',
          'Ongoing maintenance retainer',
        ],
        highlighted: true,
        note: 'Custom Enterprise Build',
      },
    ],
  },
  {
    slug: 'saas-development',
    title: 'SaaS Development',
    category: 'Development',
    description: 'Full-cycle SaaS product development — from validated MVP to multi-tenant enterprise platforms with billing, analytics, and white-label support.',
    color: '#8B5CF6',
    icon: 'Layers',
    startingFrom: 'Rs. 250,000',
    packages: [
      {
        name: 'SaaS MVP',
        price: 'Rs. 250,000',
        isCustom: false,
        features: [
          'Core feature set (5–8 features)',
          'User auth & role management',
          'Subscription billing (Stripe)',
          'Admin dashboard',
          'Basic analytics & reporting',
          '90-day support',
        ],
      },
      {
        name: 'Full SaaS Platform',
        price: 'Rs. 500,000',
        isCustom: false,
        features: [
          'Full feature set (15+ features)',
          'Multi-tenancy architecture',
          'Advanced billing plans & invoicing',
          'REST API & webhook system',
          'Third-party integrations',
          'CI/CD pipeline setup',
          '6-month support',
        ],
        highlighted: false,
      },
      {
        name: 'Enterprise SaaS',
        price: null,
        isCustom: true,
        features: [
          'Fully custom cloud-native architecture',
          'White-labelling & multi-brand support',
          'Enterprise SSO & compliance (SOC2)',
          'Dedicated team (3–5 engineers)',
          'SLA uptime guarantee',
          'Ongoing development retainer',
        ],
        highlighted: true,
        note: 'Custom Enterprise Scale',
      },
    ],
  },
  {
    slug: 'blockchain-crypto',
    title: 'Blockchain & Crypto',
    category: 'Web3 & Crypto',
    description: 'Token launches, DeFi protocols, NFT platforms, and crypto exchanges — everything needed to build, launch, and scale in the Web3 ecosystem.',
    color: '#F97316',
    icon: 'Database',
    startingFrom: 'Rs. 150,000',
    packages: [
      {
        name: 'Token / NFT Launch',
        price: 'Rs. 150,000',
        isCustom: false,
        features: [
          'ERC-20 / ERC-721 / BEP-20 token',
          'Smart contract development & audit',
          'Tokenomics design',
          'Wallet integration',
          'Launchpad / marketplace listing prep',
        ],
      },
      {
        name: 'DeFi Protocol',
        price: 'Rs. 300,000',
        isCustom: false,
        features: [
          'AMM / lending / staking protocol',
          'Liquidity pool mechanics',
          'Yield farming & reward logic',
          'Smart contract security audit',
          'Web3 dApp frontend',
          '90-day support',
        ],
        highlighted: false,
      },
      {
        name: 'Crypto Exchange / Platform',
        price: null,
        isCustom: true,
        features: [
          'Centralised or DEX architecture',
          'Order book & matching engine',
          'Multi-chain wallet support',
          'KYC / AML integration',
          'Admin portal & analytics',
          'Regulatory compliance guidance',
        ],
        highlighted: true,
        note: 'Custom Exchange Build',
      },
    ],
  },
  {
    slug: 'generative-ai',
    title: 'Generative AI',
    category: 'Artificial Intelligence',
    description: 'Custom generative AI applications — LLM-powered tools, RAG pipelines, multi-modal AI, and white-label AI platforms built for production.',
    color: '#EC4899',
    icon: 'Sparkles',
    startingFrom: 'Rs. 80,000',
    packages: [
      {
        name: 'AI Content Generator',
        price: 'Rs. 80,000',
        isCustom: false,
        features: [
          'GPT-4 / Claude / Gemini integration',
          'Custom prompt engineering',
          'Content pipeline setup',
          'API delivery + documentation',
          '30-day support',
        ],
      },
      {
        name: 'Custom LLM Application',
        price: 'Rs. 180,000',
        isCustom: false,
        features: [
          'RAG (Retrieval-Augmented Generation) pipeline',
          'Vector database integration (Pinecone / Weaviate)',
          'Custom knowledge base ingestion',
          'Chat + completion API',
          'Admin dashboard',
          '60-day support',
        ],
      },
      {
        name: 'Generative AI Platform',
        price: 'Rs. 350,000',
        isCustom: false,
        features: [
          'Multi-modal AI (text, image, voice)',
          'Custom model fine-tuning',
          'Production-grade GPU infrastructure',
          'API + SDK delivery',
          'White-label ready',
          'Dedicated AI engineering team',
          'SLA support',
        ],
        highlighted: true,
        note: 'Full Platform Build',
      },
    ],
  },
]
